package aoc
import aoc._

@main def run(): Unit =
  println("Year 2023:")
  println("  Day 1: Trebuchet?!")
  println(s"    ├ Solution #1: ${timed(day01.solve1(getInput(1)))}")
  println(s"    └ Solution #2: ${timed(day01.solve2(getInput(1)))}")
  println("  Day 2: Cube Conundrum")
  println(s"    ├ Solution #1: ${timed(day02.solve1(getInput(2)))}")
  println(s"    └ Solution #2: ${timed(day02.solve2(getInput(2)))}")
  println("  Day 3: Gear Ratios")
  println(s"    ├ Solution #1: ${timed(day03.solve1(getInput(3)))}")
  println(s"    └ Solution #2: ${timed(day03.solve2(getInput(3)))}")
  println("  Day 4: Scratchcards")
  println(s"    ├ Solution #1: ${timed(day04.solve1(getInput(4)))}")
  println(s"    └ Solution #2: ${timed(day04.solve2(getInput(4)))}")
  println("  Day 5: If You Give A Seed A Fertilizer")
  println(s"    ├ Solution #1: ${timed(day05.solve1(getInput(5)))}")
  println(s"    └ Solution #2: ${timed(day05.solve2(getInput(5)))}")
  println("  Day 6: Wait For It")
  println(s"    ├ Solution #1: ${timed(day06.solve1(getInput(6)))}")
  println(s"    └ Solution #2: ${timed(day06.solve2(getInput(6)))}")
  println("  Day 7: Camel Cards")
  println(s"    ├ Solution #1: ${timed(day07.solve1(getInput(7)))}")
  println(s"    └ Solution #2: ${timed(day07.solve2(getInput(7)))}")
  println("  Day 8: Haunted Wasteland")
  println(s"    ├ Solution #1: ${timed(day08.solve1(getInput(8)))}")
  println(s"    └ Solution #2: ${timed(day08.solve2(getInput(8)))}")
  println("  Day 9: Mirage Maintenance")
  println(s"    ├ Solution #1: ${timed(day09.solve1(getInput(9)))}")
  println(s"    └ Solution #2: ${timed(day09.solve2(getInput(9)))}")
  println("  Day 10: Pipe Maze")
  println(s"    ├ Solution #1: ${timed(day10.solve1(getInput(10)))}")
  println(s"    └ Solution #2: ${timed(day10.solve2(getInput(10)))}")
  println("  Day 11: Cosmic Expansion")
  println(s"    ├ Solution #1: ${timed(day11.solve1(getInput(11)))}")
  println(s"    └ Solution #2: ${timed(day11.solve2(getInput(11)))}")
  // println("  Day 12: Hot Springs")
  // println(s"    ├ Solution #1: ${timed(day12.solve1(getInput(12)))}")
  // println(s"    └ Solution #2: ${timed(day12.solve2(getInput(12)))}")
  println("  Day 13: Point of Incidence")
  println(s"    ├ Solution #1: ${timed(day13.solve1(getInput(13)))}")
  println(s"    └ Solution #2: ${timed(day13.solve2(getInput(13)))}")
